version: '3.8'

services:
  api:
    build:
      context: ./docker
    container_name: tsrepo_api
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3333:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine3.15
    container_name: tsrepo_postgres
    environment:
      POSTGRES_DB: testrepo
      POSTGRES_USER: testrepo
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - db_postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: tsrepo_adminer
    ports:
      - '1337:8080'
volumes:
  db_postgres:
  node_modules:
